name: Commit and Tag

on:
  push:
    branches:
      - main  # Replace with your branch if different

jobs:
  commit-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Git
        run: |
          git config user.name "Your GitHub Username"
          git config user.email "your-email@example.com"

      - name: Commit Changes
        run: |
          git add .
          git commit -m "Automated commit: $(date +"%Y-%m-%d %H:%M:%S")"

      - name: Create Tag with Timestamp
        run: |
          TIMESTAMP=$(date +"%Y%m%d-%H%M%S")
          TAG_NAME="v1.0.0-$TIMESTAMP"
          git tag -a $TAG_NAME -m "Tag created on $TIMESTAMP"
          git push origin main --tags
